// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChNu0BShOutx-l4VtI2lqNw8Q4p4ftgyM',
    appId: '1:796934946548:web:73ec0a5efdfd9f7a0d28a1',
    messagingSenderId: '796934946548',
    projectId: 'personalbudgetingapp-308b1',
    authDomain: 'personalbudgetingapp-308b1.firebaseapp.com',
    storageBucket: 'personalbudgetingapp-308b1.appspot.com',
    measurementId: 'G-21CL8LZPQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_FqbYe7NE8p4rNpPvSBoEvSM21RGILk',
    appId: '1:796934946548:android:57f6e0ad86ead4810d28a1',
    messagingSenderId: '796934946548',
    projectId: 'personalbudgetingapp-308b1',
    storageBucket: 'personalbudgetingapp-308b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAKSc6CgE9ITcpHdelu_Bp39Gt5SvgBHU',
    appId: '1:796934946548:ios:722572f9b625f0990d28a1',
    messagingSenderId: '796934946548',
    projectId: 'personalbudgetingapp-308b1',
    storageBucket: 'personalbudgetingapp-308b1.appspot.com',
    iosBundleId: 'com.example.personalBudgetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAKSc6CgE9ITcpHdelu_Bp39Gt5SvgBHU',
    appId: '1:796934946548:ios:722572f9b625f0990d28a1',
    messagingSenderId: '796934946548',
    projectId: 'personalbudgetingapp-308b1',
    storageBucket: 'personalbudgetingapp-308b1.appspot.com',
    iosBundleId: 'com.example.personalBudgetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChNu0BShOutx-l4VtI2lqNw8Q4p4ftgyM',
    appId: '1:796934946548:web:aa962249781cd15e0d28a1',
    messagingSenderId: '796934946548',
    projectId: 'personalbudgetingapp-308b1',
    authDomain: 'personalbudgetingapp-308b1.firebaseapp.com',
    storageBucket: 'personalbudgetingapp-308b1.appspot.com',
    measurementId: 'G-K1M7YGHL3F',
  );
}
